[all_vms]
k3s_server ansible_host=10.220.1.165
monitoring_server ansible_host=10.220.1.166

[monitoring]
monitoring_server

[all:vars]
ansible_user=vagrant
ansible_ssh_pass=vagrant
ansible_become=yes
